global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'data-ingestion'
    static_configs:
      - targets: ['data-ingestion:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'feature-engineering'
    static_configs:
      - targets: ['feature-engineering:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'model-serving'
    static_configs:
      - targets: ['model-serving:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'portfolio-optimization'
    static_configs:
      - targets: ['portfolio-optimization:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'alert-service'
    static_configs:
      - targets: ['alert-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'dashboard'
    static_configs:
      - targets: ['dashboard:8501']
    metrics_path: '/metrics'
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
